baseURL = 'https://quantumsocietyaustria.github.io/'
languageCode = 'en-us'
title = 'Quantum Society Austria'
theme = 'qsa'
sectionPagesMenu = "nav"

[markup]
  [markup.highlight]
    noClasses=false

[params]
  description = "An inclusive quantum computing society for Austria."
  custom_css = ["css/style.css"]