name = "QSA"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A simple theme for the Quantum Society Austria."
homepage = "https://quantumsocietyaustria.github.io"
tags = ["quantum computing", "Austria"]
min_version = "0.41.0"

[author]
  name = "Nico Einsidler"
  homepage = "ne555.io"